import React from 'react';
import './About.css';

export default function About() {
    return(
        <div className="main-about-section">
        <h2 className='about-text-content'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut pharetra. Natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Nunc scelerisque viverra mauris in aliquam sem fringilla ut. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Placerat duis ultricies lacus sed turpis tincidunt id aliquet. Et malesuada fames ac turpis egestas sed. Sit amet aliquam id diam. Vitae nunc sed velit dignissim sodales. Duis at consectetur lorem donec. Ipsum dolor sit amet consectetur adipiscing elit. Proin libero nunc consequat interdum varius sit. Mattis vulputate enim nulla aliquet. Ipsum nunc aliquet bibendum enim facilisis gravida. Nec ullamcorper sit amet risus nullam eget felis. Facilisis magna etiam tempor orci. Arcu non sodales neque sodales ut etiam sit.

Enim sit amet venenatis urna cursus. Et tortor consequat id porta. Et netus et malesuada fames ac turpis egestas maecenas pharetra. Ipsum faucibus vitae aliquet nec. Leo vel orci porta non pulvinar neque laoreet suspendisse. Sem fringilla ut morbi tincidunt augue interdum velit euismod in. Purus ut faucibus pulvinar elementum integer enim. Vel facilisis volutpat est velit egestas dui id ornare arcu. Nibh praesent tristique magna sit amet purus gravida quis blandit. Nulla at volutpat diam ut venenatis. Euismod lacinia at quis risus. Ac odio tempor orci dapibus ultrices in. Risus nullam eget felis eget nunc lobortis mattis aliquam. Nunc faucibus a pellentesque sit. Odio eu feugiat pretium nibh ipsum consequat. Leo integer malesuada nunc vel risus commodo viverra.

Dolor magna eget est lorem. Aliquam purus sit amet luctus. Orci phasellus egestas tellus rutrum. A condimentum vitae sapien pellentesque habitant. Id aliquet risus feugiat in ante metus dictum at. Felis eget velit aliquet sagittis id consectetur purus ut. Sapien et ligula ullamcorper malesuada proin libero. Orci ac auctor augue mauris augue neque gravida. Quis lectus nulla at volutpat diam ut. Mattis rhoncus urna neque viverra justo nec ultrices dui. Tellus at urna condimentum mattis pellentesque.

Id consectetur purus ut faucibus pulvinar elementum integer. Pellentesque habitant morbi tristique senectus et netus. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Feugiat scelerisque varius morbi enim nunc faucibus. Dui accumsan sit amet nulla facilisi morbi. Nulla aliquet enim tortor at auctor urna nunc id cursus. Euismod in pellentesque massa placerat duis ultricies lacus sed turpis. Faucibus et molestie ac feugiat sed lectus vestibulum. Faucibus in ornare quam viverra orci sagittis. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget egestas. Vulputate eu scelerisque felis imperdiet proin. Placerat orci nulla pellentesque dignissim enim sit amet venenatis. Egestas sed tempus urna et pharetra pharetra massa massa ultricies.

Arcu dictum varius duis at. Quam id leo in vitae turpis massa sed elementum. Condimentum mattis pellentesque id nibh tortor id aliquet lectus proin. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Amet est placerat in egestas erat. Amet volutpat consequat mauris nunc congue nisi vitae. Quis risus sed vulputate odio ut enim blandit. Aliquet eget sit amet tellus cras adipiscing enim eu. Semper eget duis at tellus at urna condimentum. Venenatis a condimentum vitae sapien pellentesque habitant. Eros donec ac odio tempor orci. Donec massa sapien faucibus et molestie. Vulputate eu scelerisque felis imperdiet proin fermentum. Elementum tempus egestas sed sed risus. Tincidunt arcu non sodales neque. Varius sit amet mattis vulputate enim nulla. Vivamus at augue eget arcu dictum varius.</h2>
        </div>
    )
}